site_name: HackaMove
nav:
  - Ktorz-net <: '..'
  - Home: 'index.md'
  - Game Rules: 'rules.md'
  - Bot player: 'bots.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style.css
