site_name: HackaMove
nav:
  - Ktorz-net <: '..'
  - Home: 'index.md'
  - Game Rules: 'rules.md'
  - first AI:
    - Bot Player: 'bots.md'
    - Distance and Paths: 'dijkstra.md'
  - Agile Dev.:
    - Iterative process: 'iterative.md'
    - Test driven: 'tests.md'
  - F.A.Q: 'faq.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - style.css
